# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Main Page Setup

# title: John Doe's Portfolio # This is what shows up in the tab of the browser
title: Ha-ves' Portfolio # This is what shows up in the tab of the browser

# Hero Section
name: Ha-ves
fullname: Hafizh Irfansyah Putra
headline: System Engineer
description: >- # dont remove this line. this will ignore all new lines until the next section
  Having 2+ years of software and hardware development experience.
  Worked on robotics research, embedded systems, UAV systems, cross-platform applications, and database design.
  Collaborated in teams to improve efficiency and solve problems. Experienced in cloud and IoT environments,
  currently seeking to apply technical expertise to challenging engineering projects.

# Place your profile image in /assets/images/profile-image/folder and edit the file name
profile_image: https://www.tekat.my.id/hafizh-profile-pic/
favicon: https://avatars.githubusercontent.com/u/20160532?v=4

# Link your resume
# You can place your resume in assets/resume/{resume.pdf or add external link such as pdf saved in google drive 
resume-url: https://www.tekat.my.id/hafizh_cv2025/


# Set up external links - this will show up as small icons next to your name.

external-links:    # input only your own url slug. The icons with missing entries will not appear.
  linkedin: havesirfan    # https://www.linkedin.com/in/{your url slug} 
  github: ha-ves    # https://github.com/{your url slug} 
  stackoverflow:       # https://stackoverflow.com/users/{your url slug}
  medium:            # https://medium.com/@{your url slug} 
  x-twitter:   # https://x.com/{your url slug} 
  threads:            # https://threads.net/@{your url slug} 
  instragram:       # https://instagram.com/{your url slug} 
  youtube:           # https://youtube.com/@{your url slug} 
  discord:            # https://discord.com/users/{your url slug} 
  bluesky:           # https://bsky.app/profile/{your url slug} 
  website: https://www.tekat.my.id
  

# Skills Section - Add the list of your Skills by categories/tools. The indentation for each level needs to be precise. 
skills:
  - category: Programming Languages
    tools:
      - C / C++
      - C#
      - Python
      - SQL
      - Lua
      # - Java
  - category: Frameworks & Libraries
    tools:
      - .NET (WPF / Xamarin.Forms)
      - ROS2
      - PyTorch
      - Detectron2
      - ONNX Runtime
      - oLLaMa
  - category: Design & Modeling
    tools:
      - 3D design (Autodesk Fusion 360)
      - PCB design (KiCad / Autodesk Eagle)
  - category: Embedded & Electronics
    tools:
      - STM32 (C / C++)
      - ESP32 / ESP8266 (Arduino / Espressif)
      - Arduino
      - AVR / Microcontroller
      - UART / Serial
      - SPI / I2C
      - GPS / IMU / Magnetometer
  - category: Networking & Protocols
    tools:
      - TCP/IP / UDP
      - MAVLink
      - Socket.IO
      - MQTT
      - Wi-Fi / Access Point
      - AES-128 encryption
  - category: Control & Robotics
    tools:
      - PID control
      - Path planning
      - Robotic arms (Kinova)
  - category: Data & Visualization
    tools:
      - Real-time data visualization
      - OxyPlot
      - SQLite
      - Dapper
  - category: DevOps / Cloud / Infra
    tools:
      - Docker / containerization
      - Virtual Private Cloud (VPC)
      - Server & domain management
      - Reverse proxies & SSL/TLS
  - category: Tools & Misc
    tools:
      - Git / GitHub
      - Game scripting & modding
      - Tool development
      - Open-source contributions

# Contact Form Setup. Setup an account and copy over the key. When someone fills out the form, it will be received in your email.
formspree-key:   # https://formspree.io/f/{8-digit key}



# Active theme (Updatethis to switch themes). Make sure to keep the indentation the samne.
colors: # this is the basic theme
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"

# A few examples. 
basic theme:
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"
  
mint theme:
  text: "#2c3333"
  border: "#e0f2ef"
  link: "#40b3a2"
  highlight: "#2a9d8f"
  background: "#f7fbfa"
  light_background: "#f0f9f7"
  
lemon theme:
  text: "#2d2926"
  border: "#f7f3e3"
  link: "#ffc94d"
  highlight: "#ffb800"
  background: "#fffdf5"
  light_background: "#fff9e6"
  
pink theme:
  text: "#2d2d2d"
  border: "#f8e2e2"
  link: "#ff8fa3"
  highlight: "#ff4d6d"
  background: "#fff8f8"
  light_background: "#fff5f6"






#########################################################################################################
# Build settings for the site. Editing the below may cause the site to malfunction.

collections:
  projects:
    output: true
    permalink: /projects/:path/


# markdown: GFM
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
